### np.sort
Return a sorted copy of an array

In [2]:
import numpy as np
a = np.random.randint(1,100,15)
print(a)

[39 96 50 44 19 54 39 61 43 94 22 81 27 94 91]


In [3]:
print(np.sort(a))

[19 22 27 39 39 43 44 50 54 61 81 91 94 94 96]


In [4]:
print(np.sort(a)[::-1])

[96 94 94 91 81 61 54 50 44 43 39 39 27 22 19]


In [5]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[[58 31 94 55]
 [57 27 93 72]
 [38 13 23 65]
 [42 19 10 73]
 [ 4 54 59 34]
 [51 40 60 10]]


In [6]:
print(np.sort(b))

[[31 55 58 94]
 [27 57 72 93]
 [13 23 38 65]
 [10 19 42 73]
 [ 4 34 54 59]
 [10 40 51 60]]


In [7]:
print(np.sort(b,axis=0))

[[ 4 13 10 10]
 [38 19 23 34]
 [42 27 59 55]
 [51 31 60 65]
 [57 40 93 72]
 [58 54 94 73]]


In [8]:
np.append(b,np.ones((b.shape[0],1)), axis=1)

array([[58., 31., 94., 55.,  1.],
       [57., 27., 93., 72.,  1.],
       [38., 13., 23., 65.,  1.],
       [42., 19., 10., 73.,  1.],
       [ 4., 54., 59., 34.,  1.],
       [51., 40., 60., 10.,  1.]])

### np.concatenate
np.concatenate() function concatenate a sequesnce of array along an existing array

In [9]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [10]:
np.concatenate((c,d),axis=0) # 0 is for rows

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.concatenate((c,d),axis=1) # 1 is for column

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique
With the help of np.unique() method, we can get the unique value form an array given as parameter in np.unique method.


In [12]:
e = np.array([1,1,1,1,2,2,2,33,3,34,4,5,5,5,6,7,8,9,0,1,11,11,2211,211,1,1221,1221])
f = np.array([[1,2,3,4],[1,1,1,1]])
print(e)
print(f)

[   1    1    1    1    2    2    2   33    3   34    4    5    5    5
    6    7    8    9    0    1   11   11 2211  211    1 1221 1221]
[[1 2 3 4]
 [1 1 1 1]]


In [13]:
print(np.unique(e))

[   0    1    2    3    4    5    6    7    8    9   11   33   34  211
 1221 2211]


In [14]:
np.unique(f)

array([1, 2, 3, 4])

### np.expand_dims
With the help of np.enpand_dims() method, we can get the expected dimension of the array

In [15]:
a = np.arange(10)
np.expand_dims(a, axis = 0)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
b = np.arange(4).reshape(2,2)
print(b.shape)
np.expand_dims(b,axis=1)

(2, 2)


array([[[0, 1]],

       [[2, 3]]])

### np.where
The np.where() function return the indices of the element is an input array where the given condition is satisfied

In [17]:
a = np.random.randint(1,100,15)
a

array([48, 56, 16, 13, 14, 23, 35, 78, 46, 89, 45, 80, 13, 20, 10])

In [18]:
# where the element is greater than 50
np.where(a > 50)

(array([ 1,  7,  9, 11]),)

In [19]:
# replace all value > 50 with 0
# np.where(condition, true, false)
np.where(a > 50 , 0, a)

array([48,  0, 16, 13, 14, 23, 35,  0, 46,  0, 45,  0, 13, 20, 10])

In [20]:
np.where(a % 2 == 0, 0, 1)

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0])

### np.argmax
The np.argmax() function return indices of the max element of the array in a particular axis.

In [21]:
a

array([48, 56, 16, 13, 14, 23, 35, 78, 46, 89, 45, 80, 13, 20, 10])

In [22]:
print(np.argmax(a))

9


In [23]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[98, 86, 42, 14],
       [96, 94, 44, 33],
       [99, 58, 80, 63],
       [55, 54, 88, 59],
       [ 3, 60, 97, 37],
       [93, 63, 16, 24]])

In [24]:
np.argmax(b)

np.int64(8)

In [25]:
np.argmax(b, axis=0)

array([2, 1, 4, 2])

In [26]:
np.argmax(b, axis=1)

array([0, 0, 0, 2, 2, 0])

### np.argmin
The np.argmin() function return indices of the min element of the array in a particular axis.

In [27]:
a

array([48, 56, 16, 13, 14, 23, 35, 78, 46, 89, 45, 80, 13, 20, 10])

In [28]:
np.argmin(a)

np.int64(14)

### np.cumsum
np.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [29]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [31]:
b

array([[98, 86, 42, 14],
       [96, 94, 44, 33],
       [99, 58, 80, 63],
       [55, 54, 88, 59],
       [ 3, 60, 97, 37],
       [93, 63, 16, 24]])

In [32]:
np.cumsum(b, axis=0)

array([[ 98,  86,  42,  14],
       [194, 180,  86,  47],
       [293, 238, 166, 110],
       [348, 292, 254, 169],
       [351, 352, 351, 206],
       [444, 415, 367, 230]])

In [33]:
np.cumsum(b, axis=1)

array([[ 98, 184, 226, 240],
       [ 96, 190, 234, 267],
       [ 99, 157, 237, 300],
       [ 55, 109, 197, 256],
       [  3,  63, 160, 197],
       [ 93, 156, 172, 196]])

### np.cumprod
np.cumprod() function is used when we want to compute the cumulative product of array elements over a given axis.

In [34]:
arr = np.arange(1,11)

In [35]:
np.cumprod(arr)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

### np.percentile
np.percentile() function used to compute the nth percentile of the given data(array elements) alang the specified axis.

In [36]:
a

array([48, 56, 16, 13, 14, 23, 35, 78, 46, 89, 45, 80, 13, 20, 10])

In [37]:
np.percentile(a, 50)

np.float64(35.0)

### np.histogram
numpy has a built_in np.histogram() function which represents the frequency of data distribution in the graphical form.

In [38]:
a

array([48, 56, 16, 13, 14, 23, 35, 78, 46, 89, 45, 80, 13, 20, 10])

In [39]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 5, 2, 1, 3, 1, 0, 1, 2, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef
Return pearson product- moment correlation coefficient

In [41]:
salary = np.array([20000,40000,25000,35000,60000])
exp = np.array([1,3,2,4,2])
np.corrcoef(salary, exp)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin
With the help of np.isin() method, we can see that one array having values are checked in a different numpy array having different elements with differents sizes.

In [43]:
a

array([48, 56, 16, 13, 14, 23, 35, 78, 46, 89, 45, 80, 13, 20, 10])

In [49]:
item = np.arange(20)
a[np.isin(a, item)]

array([16, 13, 14, 13, 10])

### np.flip
The np.flip() functions reverses the order of array elements along the specified axis, preserving the shape of the array.

In [50]:
a

array([48, 56, 16, 13, 14, 23, 35, 78, 46, 89, 45, 80, 13, 20, 10])

In [51]:
np.flip(a)

array([10, 20, 13, 80, 45, 89, 46, 78, 35, 23, 14, 13, 16, 56, 48])

In [52]:
b

array([[98, 86, 42, 14],
       [96, 94, 44, 33],
       [99, 58, 80, 63],
       [55, 54, 88, 59],
       [ 3, 60, 97, 37],
       [93, 63, 16, 24]])

In [53]:
np.flip(b)

array([[24, 16, 63, 93],
       [37, 97, 60,  3],
       [59, 88, 54, 55],
       [63, 80, 58, 99],
       [33, 44, 94, 96],
       [14, 42, 86, 98]])

### np.put
The np.put() method replace specific element of an array with given value of p_array. Array indexed works on flatted array.

In [55]:
a

array([48, 56, 16, 13, 14, 23, 35, 78, 46, 89, 45, 80, 13, 20, 10])

In [58]:
# this will change the array parmanently
np.put(a,[0,1],[4800,5600])

In [59]:
a

array([4800, 5600,   16,   13,   14,   23,   35,   78,   46,   89,   45,
         80,   13,   20,   10])

### np.delete
The np.delete() function return a new array with the deletion of subarray along with the mentioned axis.

In [65]:
a

array([4800, 5600,   16,   13,   14,   23,   35,   78,   46,   89,   45,
         80,   13,   20,   10])

In [66]:
np.delete(a,0)

array([5600,   16,   13,   14,   23,   35,   78,   46,   89,   45,   80,
         13,   20,   10])

In [67]:
np.delete(a,[0,1,2,3])

array([14, 23, 35, 78, 46, 89, 45, 80, 13, 20, 10])

### Set functions
np.union1d

np.intersect1d

np.setdiff1d

np.setxor1d

np.in1d

In [68]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [70]:
np.intersect1d(m,n)

array([3, 4, 5])

In [71]:
np.setdiff1d(m,n)

array([1, 2])

In [73]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [78]:
np.in1d(m,1)

/tmp/ipykernel_1519/3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

### np.clip
np.clip() function is used to clip(limit) the values in an array.

In [80]:
a

array([4800, 5600,   16,   13,   14,   23,   35,   78,   46,   89,   45,
         80,   13,   20,   10])

In [81]:
np.clip(a,a_min = 25, a_max = 75)

array([75, 75, 25, 25, 25, 25, 35, 75, 46, 75, 45, 75, 25, 25, 25])

In [ ]:
# 17. np.swapaxes
# 18. np.uniform
# 19. np.count_nonzero
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5
# 25. np.allclose and equals
