### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D array
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


1D array - vector

2D array - matrix

3D array - tensor

In [ ]:
# float data type array
d = np.array([1,2,3], dtype = float)
print(d)

[1. 2. 3.]


In [12]:
# np.arange
num = np.arange(1,11)
print(num)

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
# with reshape
shape = np.arange(1,11).reshape(2,5)
print(shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
# np.ones and np.zeros
ones = np.ones((3,4))
print(ones)

print()
zeros = np.zeros((3,4))
print(zeros)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
# np.random
random = np.random.random((3,4))
print(random)

[[0.25090307 0.9263152  0.14267323 0.43938924]
 [0.25561639 0.34034343 0.78627053 0.45549545]
 [0.18412537 0.87692738 0.93698342 0.16978297]]


In [33]:
# np.linspace
arr = np.linspace(-10, 10, 10) # here we provide (lower_range, upper_range, no_of_item_you_want_to_generate)
print(arr)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [35]:
# np.identity
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Array Attributes

In [57]:
a1 = np.arange(10, dtype = np.int32)
a2 = np.arange(12, dtype= float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [44]:
# ndim -> it will give the dimension of the array
a1.ndim
a2.ndim
a3.ndim

3

In [49]:
# shape -> it will give the number of item in each dimension
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [54]:
# size -> it tells number of item in np array
a3.size
a2.size
a1.size

10

In [63]:
# itemsize
print(a1.itemsize) # 32 bit integer
print(a2.itemsize) # float
print(a3.itemsize) # 64 bit integer

4
8
8


In [65]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [69]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array operations

In [72]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print()
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


#### Scalar Operations

In [75]:
# Arithmetic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [77]:
# relational
a2 > 5
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

### Vector Operations

In [79]:
# arithmetic
a1 + a2
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

## Array Fucntions

In [82]:
a1 = np.random.random((3,3))
print(a1)
a1 = np.round(a1*100)
print(a1)

[[0.47670644 0.8750671  0.94474508]
 [0.37832134 0.45870051 0.95891746]
 [0.05111362 0.48485731 0.07853614]]
[[48. 88. 94.]
 [38. 46. 96.]
 [ 5. 48.  8.]]


In [90]:
# max/min/sum/prod
# axis = 0 -> col, axis = 1 -> row
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

print(a1)
print(np.max(a1,axis=1))

96.0
5.0
471.0
127928012636160.0
[[48. 88. 94.]
 [38. 46. 96.]
 [ 5. 48.  8.]]
[94. 96. 48.]


In [93]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

52.333333333333336
48.0
32.324741126401754
1044.888888888889


In [94]:
# trigonometric functions
np.sin(a1)

array([[-0.76825466,  0.0353983 , -0.24525199],
       [ 0.29636858,  0.90178835,  0.98358775],
       [-0.95892427, -0.76825466,  0.98935825]])

In [105]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [109]:
# log and exponent
np.log(a2)
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [117]:
# round/ floor / ceil
numarr = np.random.random((2,3))*100
print(numarr)
print()
print(np.round(numarr))
print()
print(np.floor(numarr))
print()
print(np.ceil(numarr))


[[ 3.50299658 82.78663801 14.66149797]
 [41.34997372 67.00703247 99.01972511]]

[[ 4. 83. 15.]
 [41. 67. 99.]]

[[ 3. 82. 14.]
 [41. 67. 99.]]

[[  4.  83.  15.]
 [ 42.  68. 100.]]


### Indexing and Slicing

In [168]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

In [120]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
print(a1[2])

2


In [125]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
print(a2[1][3])
print(a2[1,3])

7
7


In [169]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [137]:
print(a3[0][1][1])
print(a3[0, 1, 1])

3
3


In [139]:
print(a1)
print(a1[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [140]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
a2[0,:]

array([0, 1, 2, 3])

In [144]:
a2[0,1:3]

array([1, 2])

In [146]:
a2[:,2]

array([ 2,  6, 10])

In [149]:
print(a2[1:, 1:3])

[[ 5  6]
 [ 9 10]]


In [157]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [159]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [162]:
a2[1,::3]

array([4, 7])

In [164]:
a2[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [171]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [180]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [181]:
a3[0,1]

array([3, 4, 5])

In [192]:
a3[1, :, 1]

array([10, 13, 16])

In [195]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [183]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [202]:
a3[::2, 0, 0::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [203]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [204]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [216]:
for i in a2: # it will print one row at a time
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [215]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [205]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [213]:
for i in a3: # this loop will print a 2D array at a time
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [214]:
# if we want to print all item then we use np.nditer() function
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [221]:
# reshape
a = np.arange(16)
print(a)
newa = a.reshape(4,4)
print(newa)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [228]:
# transpose
a = np.arange(12).reshape(3,4)
print(a)
print()
newt = np.transpose(a)
print(newt)
print()
print(a.T) # simple syntax for transpose

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [229]:
# ravel -> convert any dimension array into 1D
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [231]:
print(np.ravel(a2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [232]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [234]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [239]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [241]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [242]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [243]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [244]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [245]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [249]:
# horizontal splitting
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [253]:
# vertical splitting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]